### ISSUE TITLE
allow usage without meross cloud

### ISSUE THREAD

**Issue by pciavald** [albertogeniola/meross-homeassistant#102]
Hi, 

I've received the Meross plugs and i've [set them to use my local MQTT](https://github.com/albertogeniola/MerossIot/issues/1#issuecomment-648112885) broker. I'd like to try this plugin but it asks for the username/pass of the Meross cloud, of which I don't even have an account. The plugs are talking directly to the MQTT broker (over TLS on port 8883), and HA is connected to the broker without TLS on port 1883.

Would it be possible to connect to the custom broker instead of Meross' ?

Thanks

**Comment by skullydazed** [comment]
I've spent my weekend working on my own proof of concept for this, but done entirely outside of MerossIot, <https://github.com/skullydazed/meross_mqtt_ha>. Now that I understand how that all works and have a working prototype, I'd like to throw it away and build my real version. 

ISTM that MerosIot and meross-homeassistant does most of what I need already, but I'm still trying to grok how it all fits together. I think that some work will need to be done on `meross_iot.manager.MerossManager` and the custom component to remove http client assumptions, but once that's done using my local MQTT broker instead of iot.meross.com should be possible.

Am I on the right track here?

**Comment by lukejagger** [comment]
I think so, and it would be amazing to integrate the local handling with this, for a complete solution.  There are lots of ocassions where the cloud is unresponsive and local handling would be incredibly useful!

**Comment by albertogeniola** [comment]
Hey guys, it's time: #144 .
