### ISSUE TITLE
Add support for msg200 smart garage door opener

### ISSUE THREAD

**Issue by apippin** [albertogeniola/meross-homeassistant#179]
I just bought and installed the Meross msg200 smart garage door opener. After installing this add-on (version 1.0.5) via HACS and setting up the integration, it does not appear to support this opener:

```
===============================
Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.1.0rc7
-------------------------------
This custom component is under development and not yet ready for production use.
In case of errors/misbehave, please report it here: 

If you like this extension and you want to support it, please consider donating.
-------------------------------
List of devices reported by HTTP API:
- Smart Garage Door Opener (msg200) - OnlineStatus.OFFLINE
===============================
2020-12-09 12:48:02 ERROR (MainThread) [meross_iot.device_factory] Could not find any known device class for device type (msg200).
2020-12-09 12:48:02 ERROR (MainThread) [meross_iot.manager] Could not build statically device Smart Garage Door Opener (2007020265518690818148e1e92343d1) as it's not a known type.
```

The meross app does show the opener as being online and can be operated from the app without any issues. 

UPDATE:
After waiting a few minutes, and reloading the integration, it now appears to work properly:
```
===============================
Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.1.0rc7
-------------------------------
This custom component is under development and not yet ready for production use.
In case of errors/misbehave, please report it here: 
https://github.com/albertogeniola/meross-homeassistant/issues

If you like this extension and you want to support it, please consider donating.
-------------------------------
List of devices reported by HTTP API:
- Smart Garage Door Opener (msg200) - OnlineStatus.ONLINE
===============================
```
So maybe the issue is just when it is offline in terms of the error messages above. 

Another issue I have seen with the msg200 is some timeouts from time to time from the async_execute_cmd() call. It looks like it defaults to 5 seconds. It would be nice if the timeout was configurable to support more latent environments and connections. I've found that by increasing the default timeout in manager.py,  I'm not seeing the timeouts any more.

**Comment by albertogeniola** [comment]
Hi @apippin ,
The latest versions of the Meross Components are able to add devices to Homeassistant even if they are offline. This is possible thanks to "cached" known device classes, that are hard-coded within the component logic. However, the msg200 garage opener is rather new device and I do not own one, so that device class is not available until the msg200 comes online. As you discovered, it is enough to start Homeassistant when the device is online. 

About the timeout management, that could be an option to add to Homeassistant component configuration. I'm curious about your specific case: how long is your current timeout limit?
