### ISSUE TITLE
Smart Thermostatic Valves (mts100v3) are not available any more. Cannot be commanded any longer

### ISSUE THREAD

**Issue by Neuforge** [albertogeniola/meross-homeassistant#182]
Hello, 

Since a few days, my Meross smart thermostatic valves are not available any more for displaying the temperature or receiving commands to / from Home Assistant. I have a number of routines that were sending commands to the valves, but these are now ineffective. 

I don't know if the problem comes form a change of firmware in Meross, a change in the Meross cloud, or, ... 

Anyone else has the same issue, and possibly a solution? 

Thank you all. 

Denis.

**Comment by jono23872** [comment]
Mine still working. But every few days Meross Cloud bans me and I have to ask them to reset my service, which takes 24 hours. During this 24 hour period, I can controll locally with the Meross Android App, but HA reports them unavailable. Only affects my thermostats, not my switches and sockets. I did upgrade with Alberto's latest integration a month or so ago, which improved things for a short while, but it looks like Meross simply counteract and become more and more strict.

**Comment by albertogeniola** [comment]
Hi @Neuforge ,

@jono23872 is right, unfortunately the Meross guys are not being collaborative, quite the opposite.
In any case: can you provide the HW and SW version of your thermostat valve? @jono23872 can you do the same so we can compare?

**Comment by jono23872** [comment]
Hi Alberto
Firstly just to say what an amazing person you are to do all this stuff, and shame of Meross for being uncollaborative! They don't realize it, but they're shooting themselves in the foot because it will become more and more obvious that other brands are more capable and less troublesome - like Tado for example. There was a scathing report from Which? a couple of months ago too about the security of some of their products - so you'd think they'd be keen to get a good name, not a bad one?
I have 7 MTS100V3 valves which I spent quite a bit on, but I'm seriously considering replacing with Tado now - at huge cost... because my simple requirement is "when a radiator needs heat, turn boiler call for heat switch on. When no radiators need heat, turn boiler call for heat switch off". The fact that in 2020 (soon 2021) we have so called "smart" devices that cannot, natively, perform the most fundamental and basic of actions, is frankly shocking. Thankfully we have you and your amazing work with Meross devices and the Home Assistant integration which made it all possible, but then Meross themselves start to become even more difficult!?

Anyway - to provide the info you asked:

My Smart Hub is:
msh300
firmware version 4.1.26
hardware version 4.0.0

I'm not of the firmware version of the valves...
In HA they are as follows:
Device info
mts100v3 unknown
by Meross
Firmware: unknown

In the Meross app I cannot find any info on them.

Hope that helps somehow and please, if there is anything else I can do to help you, let me know.

Jono.

**Comment by Neuforge** [comment]
Hello Jono, how do you do that reset? 

 

Thanks.

 

Denis. 

 

De : jono23872 <notifications@github.com>
Répondre à : albertogeniola/meross-homeassistant <reply@reply.github.com>
Date : mercredi 30 décembre 2020 à 08:39
À : albertogeniola/meross-homeassistant <meross-homeassistant@noreply.github.com>
Cc : Neuforge <denis@neuforge.com>, Author <author@noreply.github.com>
Objet : Re: [albertogeniola/meross-homeassistant] Smart Thermostatic Valves (mts100v3) are not available any more. Cannot be commanded any longer (#182)

 

Mine still working. But every few days Meross Cloud bans me and I have to ask them to reset my service, which takes 24 hours. During this 24 hour period, I can controll locally with the Meross Android App, but HA reports them unavailable. Only affects my thermostats, not my switches and sockets. I did upgrade with Alberto's latest integration a month or so ago, which improved things for a short while, but it looks like Meross simply counteract and become more and more strict.

**Comment by jono23872** [comment]
Hi Denis,

If you received an email from Meross, (it usually goes into Spam/Junk for me, so be sure to check there), that looks like below... then you have to turn off your home assistant and email cloudservice@meross.com. Usually I email them and falsely charm them with niceties - "Dear Meross, thank you for being concerned about my security. I have checked and can confirm that I have not been hacked. I have also tweaked my automations to ensure the frequency of message to Meross cloud is reduced. Please re-enable my services, Thank you." Then, usually after 24 hours, the red light on my Meross hub goes green again, and then I can switch on Home Assistant and the Meross integration for HA works again... until the next time Meross blocks it, at which time I do the same again.

> Dear Customer, 
> 
> This is meross cloud security team contacting you. 
> First of all, thanks for purchasing meross and we hope that you enjoy life with our smart products. 
> Recently our cloud security system has noticed that your devices are communicating with the could server at an extremely high frequency. We consider these behaviors abnormal and are concerned about the security of your devices. 
> Due to the security concerns and the intent to avoid any further potential damage, we will terminate the cloud services of these devices for now. 
> If you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to no more than one message every ten seconds and then send an email to <cloudservice@meross.com>. We will resume cloud service for you within 24 hours. Please note that any abnormal high cloud request frequency will cause cloud service termination again. 
> Should you have any information you would like to provide us with or would like to offer us any clarification, please contact us within 24 hours. 
> 
> Thanks! 
> meross Cloud Security Team 
>_

**Comment by albertogeniola** [comment]
Hi @jono23872 

Thanks a lot for the motivation :) Always welcomed.
Speaking about thermostat Valves, it is curious that the "banning" does not propagate to all the other devices, isn't it? From what I understood, Meross just bans the valves (or better, the smart hub), while leaving the other sockets well functioning, right?

If that's the case, I believe there is still a way to improve the library and implement some sort of "multi-command" call: from what I've seen so far, Meross hubs should support multi-commands (i.e. sending multiple commands at once), but I was unable to test and implement that as I only own a single Thermostat Valve (which I bought only for testing purposes). I'll see if I can get my hands on other valves in the short term and try to figure this out.

**Comment by jono23872** [comment]
Hi Alberto

Happy New Year!

Yes - it is always only the smart hub that gets banned. I have 7 TRVs and 1 temp/humidity sensor that works through the hub. They all stop working in the cloud when banned, but they still work locally from the Meross App when on the same WiFi network.

I also have an mss510x switch, and two mss310 sockets - all of these continue to work fine even when "banned". 

So yes, it seems it is only the hub that is banned. Indeed it gets a red LED when banned and usually goes back to green within 24 hours after my begging email to them - although they banned me again yesterday morning and now 32 hours later it hasn't been re-enabled... that is the first time that has happened, so maybe they are trying to get rid of me altogether! :)

It is also interesting that the banning email always says "Please first lower your periodic request rate to no more than one message every ten seconds" - not sure if that is just a generic phrase in a generic message, and also not sure what a "message" actually is there. I mean, also, it may be that things are fine for hours and hours and then suddenly there is more than one message in a 10 second interval that triggers an alert to them? Who knows. I also wondered if the fact that I have seven TRVs might increase my chances (7 fold?) of there being more than one message in a 10 second interval from HA?

Anyway - I'm gonna buy you some more coffee in the New Year!

Also, if I can help in any other way please let me know. For example, I could give you remote access to a VM on my LAN if you wanna check out my Meross stuff if it helps you? Let me know.

Jono.

**Comment by albertogeniola** [comment]
Hi @jono23872 ,

thanks a lot for the precious info. I see there are multiple improvements possible here: one of them is definitely implementing the multi-command mode. In the meantime, would you please provide the code of the automation you use to command the boiler power socket? Maybe there is something in the logic that is causing too many messages being sent to the Meross cloud...

**Comment by jono23872** [comment]
Indeed my code is probably terrible! (Embarrassed, but here it is):

Here is the code for the automation to turn the boiler on:

`alias: Turn Boiler On
description: Turn Boiler On
trigger:
  - platform: time_pattern
    minutes: /3
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: climate.annexe_trv_mts100v3
        state: heat
      - condition: or
        conditions:
          - condition: state
            entity_id: climate.entrance_hall_trv_mts100v3
            state: heat
      - condition: or
        conditions:
          - condition: state
            entity_id: climate.office_trv_mts100v3
            state: heat
      - condition: or
        conditions:
          - condition: state
            entity_id: climate.lounge_trv_mts100v3
            state: heat
      - condition: or
        conditions:
          - condition: state
            entity_id: climate.2nd_fl_landing_trv_mts100v3
            state: heat
      - condition: or
        conditions:
          - condition: state
            entity_id: climate.2nd_bed_trv_mts100v3
            state: heat
      - condition: or
        conditions:
          - condition: state
            entity_id: climate.main_bed_trv_mts100v3
            state: heat
action:
  - type: turn_on
    device_id: 36a875c4325811eb95a09f93de855bd8
    entity_id: switch.heating_switch_mss510x_main_channel
    domain: switch
mode: single
`
And here is the code for the automation to turn the boiler off:

`alias: Turn Boiler Off
description: Turn Boiler Off
trigger:
  - platform: time_pattern
    minutes: /3
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.annexe_trv_mts100v3
        state: heat
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.entrance_hall_trv_mts100v3
        state: heat
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.office_trv_mts100v3
        state: heat
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.lounge_trv_mts100v3
        state: heat
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.2nd_fl_landing_trv_mts100v3_temperature_sensor_degc_0
        state: heat
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.2nd_bed_trv_mts100v3
        state: heat
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.main_bed_trv_mts100v3
        state: heat
action:
  - type: turn_off
    device_id: 36a875c4325811eb95a09f93de855bd8
    entity_id: switch.heating_switch_mss510x_main_channel
    domain: switch
mode: single
`

**Comment by jono23872** [comment]
Actually just looking at that now and thinking... maybe it's because I check all seven devices, twice, at one time every three minutes.. maybe I should try spread them out - but not sure how to do that for the boiler off automation, because the boiler should only be off if ALL TRVs are not state "heat" at one given time.

**Comment by ChrisPiel70** [comment]
So today it is my turn to become the "security mail". 

As jono23872 described, the LED on my msh300 is red and the Vales are unavailable in HA.
I have 1x msh300 (fw: 4.1.26, hw: 4.0.0) with 8 mts100v3 Valves (now only in the Android App available).

I only have a daily schedules which set a day / night temperatures and i have the temperture sensors in HA deactiviert.

I also have: 
Roller: 1x mrs100, 
Lights: 2x msl420, 2x msl100r, 
Power: 4x mss310, 1x mss425e, 1x mss620
(as  jono23872 described, these are not affected ???)

Not sure if its related but as i added the 2 msl420 Lights as Christmas i get this error message in HA (and all devices were unavailable) everytime i had to restart HA, and i takes a lot of time before the devices are available.

2020-12-26 16:29:24 ERROR (MainThread) [meross_iot.manager] The current API rate exceeds the overquota limit (1000.000000 %). The call will be dropped.
2020-12-26 16:29:24 ERROR (MainThread) [custom_components.meross_cloud] Error occurred.
Component version: 0.4.1.0rc7
Device info:
<Unavailable>
Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/meross_cloud/__init__.py", line 143, in async_setup_entry
    await manager.async_device_discovery()
  File "/srv/homeassistant_38/lib/python3.8/site-packages/meross_iot/manager.py", line 262, in async_device_discovery
    enrolled_devices = await asyncio.gather(*tasks, loop=self._loop)
  File "/srv/homeassistant_38/lib/python3.8/site-packages/meross_iot/manager.py", line 316, in _async_enroll_new_http_dev
    res_abilities = await self.async_execute_cmd(destination_device_uuid=device_info.uuid,
  File "/srv/homeassistant_38/lib/python3.8/site-packages/meross_iot/manager.py", line 609, in async_execute_cmd
    raise RateLimitExceeded()
meross_iot.model.exception.RateLimitExceeded
2020-12-26 21:17:00 WARNING (MainThread) [homeassistant.config_entries] Config entry for meross_cloud not ready yet. Retrying in 40 seconds
2020-12-26 21:17:15 WARNING (MainThread) [meross_iot.device_factory] Device Smart Hub (msh300, uuid 1910230414533426280248e1e910843a) reported ability Appliance.Digest.Hub. Assuming this is a full-featured HUB.
2020-12-26 21:17:40 WARNING (MainThread) [custom_components.meross_cloud]

After i turned then off  and deleted them in the Android App i was able to restart Ha without this error message.

**Comment by ChrisPiel70** [comment]
sorry, forgot to say that a just added 4 Valves shortly before Christmas.

**Comment by jono23872** [comment]
Hi Chris

Sorry to hear you got banned.

Actually, usually when my hub light goes red I email them and then 24 hours later it is green again.

However, since Christmas I have been banned twice and on despite emailing them with the usual message, the light did not go green again. After about 48 hours in each case I power cycled the hub, only to find it was reset back to factory (with flashing green light) and had to setup all my devices again from scratch in the app.

Luckily, during setting them all up again in the app, giving the devices the same names as before means that they don't need re-setting up in HA and HA automations. 

I know this is not what this forum wants to hear, but yesterday I decided to ditch Meross for the heating and took advantage of New Year bargains on Tado equipment instead. Tado seem to have several advantages (for me) over Meross in the heating arena - they have a boiler switch to call for heat natively, they have official HA integration, they have wireless wall mount thermostat controls to put on the wall in each room as well as the smart radiator valves, (all still controllable through app or HA), and you can define which one of multiple devices in the room determines whether heat is required (a room lead device). 

Some people say that Tado could start charging a subscription at some point for their cloud stuff, but I don't care about that. I even offered to pay Meross a monthly fee to stop banning me but they refused to accept.

My Meross MTS100V3s are now for sale on eBay, but if they don't sell there then let me know if you guys and gals are interested in them - postage costs (and Brexit) permitting.

I continue to use the Meross smart plugs, power strip and light switches.

Jono.

**Comment by ChrisPiel70** [comment]
Hi Jono,

Yes it very annoying and does not increase the WAF (especially in winter)!

I will look into the Tado Valves. I can send as least 4 Meross valves back to amazon untl 31 january.

**Comment by jono23872** [comment]
I agree and sympathize with the WAF issue too! Lol! Especially over Christmas!
In fact, similar principle, the whole reason I went down the smart radiator valve road in the first place is because I have a separate bedroom which I host on AirBnB, and I wanted guests to be able to set their own room temperature, and not have to keep the boiler on all the time. Meross have failed me dismally in that regard. On several occasions, -2 degrees outside and my guests turned the heating up, but radiators remained cold. On the heating front, Meross are not "smart" at all and certainly not "IoT" if all they do is ban users from the "I" in "IoT".

**Comment by jono23872** [comment]
Here's an email I had from them back in November - it is so contradictory. On the one had they say their valves status can't be used to command other devices, and they say they don't support this, that and the other..... then they actaully point me in the direction of Alberto's work... but then they ban us for using it!?

_From: Meross Support <support@meross.com> 
Sent: 25 November 2020 03:17
To: Jono 
Cc: cloudservice <cloudservice@meross.com>
Subject: Re: Re: ATTENTION: Service Termination of Your meross Smart Device due to Security Concerns [#00045662]

-- reply above this line --

Hi Jono,

Thank you for your messages.

For meross app, only the smart temperature and humidity sensor MS100 can trigger other of meross smart devices, such as the MSS510X. Unfortunately, we currently do not have any official API for end users, and we are not sure how did you setup the home assistant. Please check your settings and make sure the home assistant doesn't request meross cloud server connection at a high rate (no more than one message every ten seconds).

Besides, if you have interest in integrating meross devices to other IoT servers, please take a look at below website:

https://github.com/albertogeniola/MerossIot 

Have a nice day!

Best regards, 
Fiona 
Meross Customer Support

_

**Comment by ChrisPiel70** [comment]
I have hat enought. No response from Meross. 

So i controlled my amazon account buys and i kann return 5 from 8 Valves back to Amazon until 31 january, and this is what i am gpoing to do. Found the tado Valves are on sale (tink.de). Will first try them "offline" with HA Homekit integration.

**Comment by Neuforge** [comment]
OK guys, 

 

They have re-enabled my account. Do you know of any way to lower the number of events / API calls, so that this does not reoccur? 

 

Thanks. 

 

Denis. 

 

De : jono23872 <notifications@github.com> 
Envoyé : samedi 2 janvier 2021 12:11
À : albertogeniola/meross-homeassistant <meross-homeassistant@noreply.github.com>
Cc : Neuforge <denis@neuforge.com>; Mention <mention@noreply.github.com>
Objet : Re: [albertogeniola/meross-homeassistant] Smart Thermostatic Valves (mts100v3) are not available any more. Cannot be commanded any longer (#182)

 

Here's an email I had from them back in November - it is so contradictory. On the one had they say their valves status can't be used to command other devices, and they say they don't support this, that and the other..... then they actaully point me in the direction of Alberto's work... but then they ban us for using it!?

_From: Meross Support support@meross.com <mailto:support@meross.com> 
Sent: 25 November 2020 03:17
To: Jono
Cc: cloudservice cloudservice@meross.com <mailto:cloudservice@meross.com> 
Subject: Re: Re: ATTENTION: Service Termination of Your meross Smart Device due to Security Concerns [#00045662]

-- reply above this line --

Hi Jono,

Thank you for your messages.

For meross app, only the smart temperature and humidity sensor MS100 can trigger other of meross smart devices, such as the MSS510X. Unfortunately, we currently do not have any official API for end users, and we are not sure how did you setup the home assistant. Please check your settings and make sure the home assistant doesn't request meross cloud server connection at a high rate (no more than one message every ten seconds).

Besides, if you have interest in integrating meross devices to other IoT servers, please take a look at below website:

https://github.com/albertogeniola/MerossIot

Have a nice day!

Best regards,
Fiona
Meross Customer Support

_

**Comment by ChrisPiel70** [comment]
My account was also re-enabled this morning.

**Comment by gfrare** [comment]
> Hi @jono23872 ,
> 
> thanks a lot for the precious info. I see there are multiple improvements possible here: one of them is definitely implementing the multi-command mode. In the meantime, would you please provide the code of the automation you use to command the boiler power socket? Maybe there is something in the logic that is causing too many messages being sent to the Meross cloud...

Hi, 
I've 6 valve with 1 hub and 1 smart surgery and also in my case only the hub is banned.

**Comment by gianlucaromito** [comment]
I think I've the same problem but I "lost" all my valves in the app too. It is the second time that I add the valves to the app, then I add them to HA and after a few days the valves disappear from HA and from the APP...

**Comment by albertogeniola** [comment]
Duplicate of #250
