### ISSUE TITLE
Service Termination of Your meross Smart Device due to Security Concerns

### ISSUE THREAD

**Issue by Chaosflori25** [albertogeniola/meross-homeassistant#197]
**Describe the bug**
The API request to often so meross temporary shut down my account. Then they contacted my via Mail with this title:
"ATTENTION: Service Termination of Your meross Smart Device due to Security Concerns"
and how I should go on from this
"If you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to no more than one message every ten seconds and then send an email to <cloudservice@meross.com>. We will resume cloud service for you within 24 hours. Please note that any abnormal high cloud request frequency will cause cloud service termination again. "
**Your environment**
HomeAssistant version: core-2021.1.4
Hardware environment: Raspi 3

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```

**Comment by RebelElephant** [comment]
I received the same notification. Now I am unable to use my smart plugs.

**Comment by gfrare** [comment]
Same situation.

**Comment by mezzagianni** [comment]
Same situation.
Hub + n.7 TRV MTS100v3
Version HA Core = core-2021.1.5
Version Supervisor = supervisor-2021.01.7
Meross Cloud IoT integration = 1.0.5

**Comment by yauyauwind** [comment]
Banned, when I use the plugin over ver. 1
how can I use ver. 1 to the latest HA 2021.1.5?
I tried modified the manifest.json on the ver.1 
change the  context to "requirements": ["meross-iot==0.4.1.0rc7"],
but still unable to load
this modified can only work before the HA 1.18.3
however the custom components on the previous HA version with security issue
so that I need to update the HA to the latest version
but when I use latest HA and 1.05 then got banned 2 times, only work around 6 hours then banned
I use ver 1 plugin without banned, but when I tried to update plugin to V1.03 got banned
V1.05 banned
anyway to use V1 on latest HA? or how can I use V1.05 without banned?
I also tried to modified the _init_.py on V1.05 to lower the freq. or value, but still banned

Pls help

Thanks~~

**Comment by andreascarsetto** [comment]
Same situation.

**Comment by yauyauwind** [comment]
Meross Terminated my service over 3 days, and email support not replied
what can I do? need reset the power bar and register a new account??

**Comment by andreascarsetto** [comment]
this morning the calls started working again (and I didn't write to meross to reactivate them) ...

**Comment by yauyauwind** [comment]
Finally I full reset my 2 banned power bar
now online again
but I didn't use on HA, seem need to wait another version release
I setup google assistant, but google assistant device can't add to HA
not like the Apple Homekit, the Homekit device can be added to the HA via HomeBridge

**Comment by imac13kathleen** [comment]
Same issues as above.  I imagine I have an abnormally high number of Meross devices.  15 x smart plug minis, 2 x 3 way wall switch, 1 x outdoor plug, 3 x dimmer switches, 7 wall switches.  So 30 devices total.  None are apple homekit enabled, so that wasn't an option for me as yauyauwind mentioned.  I tried various ways to get these integrated in HA.  I'm hopeful that Albert will find us a solution for local control - but in the meantime I'm using SmartThings as an intermediary cloud layer.  So Register in the Meross App.  Join the Meross account to SmartThings.  Use the SmartThings HA Integration.  It's cloud based, but response is very good, and HA integration is perfect.

**Comment by Overheadtv** [comment]
I have two smart bulbs. They were working okay until just the other day, Mar 20. They now turn on/off at about 3-8 second rate. When they start flashing cannot stop it without powering down and resetting bulbs and re-config. Works okay with Meross app then when turn on with HA they start flashing.

Meross has banned me for excessive use.

Dear Customer,

This is meross cloud security team contacting you.
First of all, thanks for purchasing meross and we hope that you enjoy life with our smart products.
Recently our cloud security system has noticed that your devices are communicating with the could server at an extremely high frequency. We consider these behaviors abnormal and are concerned about the security of your devices.
Due to the security concerns and the intent to avoid any further potential damage, we will terminate the cloud services of these devices for now.
If you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to no more than one message every ten seconds and then send an email to <cloudservice@meross.com>. We will resume cloud service for you within 24 hours. Please note that any abnormal high cloud request frequency will cause cloud service termination again.
Should you have any information you would like to provide us with or would like to offer us any clarification, please contact us within 24 hours.

Thanks!
meross Cloud Security Team

Also found this in logs:
2021-03-20 20:08:09 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'meross_cloud'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'meross_cloud'

**Comment by githubjles** [comment]
Hi, have been any advances in this issue? I’ve been banned various times and cant enable the integration until it works.
Thanks

**Comment by albertogeniola** [comment]
duplicate of #250
