### ISSUE TITLE
ERROR AFTER APGRADE TO THE LAST VERSION

### ISSUE THREAD

**Issue by giugit** [albertogeniola/meross-homeassistant#322]
**Describe the bug**
Logger: homeassistant.config
Source: config.py:464
First occurred: 13:18:51 (1 occurrences)
Last logged: 13:18:51

Invalid config for [meross_cloud]: required key not provided @ data['meross_cloud']['http_api_endpoint']. Got None required key not provided @ data['meross_cloud']['skip_mqtt_cert_validation']. Got None. (See /config/configuration.yaml, line 234). Please check the docs at https://www.home-assistant.io/components/meross_cloud

**Your environment**
HomeAssistant version: -- Home Assistant 2021.12.10 -- core-2021.12.10
Hassio Version (if applicable): -- supervisor-2021.12.2 --
Hardware environment: -- PLEASE SPECIFY --

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```

**Comment by albertogeniola** [comment]
Hi @giugit .
That happens because the component now needs a new configuration key to be set-up in order to work correctly. To make it work you should:
1. Uninstall the previous version of the integration
2. Reboot HA
3. Install the new version of the integration via HACS/manul copy-paste
4. Reboot HA
5. Configure the integration via HA ("Add new integration").

That should make it.

**Comment by giugit** [comment]
Very Thanks Solved
