### ISSUE TITLE
Adding new plugs after initial setup doesn't propagate to HA

### ISSUE THREAD

**Issue by charan28** [albertogeniola/meross-homeassistant#402]
**Describe the bug**
It looks like new devices added to meross after the initial home assistant configuration is done aren't found by the plugin.

**Your environment**
HomeAssistant version: 2022.11.2
Hardware environment: Pi4

**Steps to reproduce**

1. Have at least one plug configured in meross app
2. Follow plugin setup for HA, will see that plug in HA
3. Add a new plug in meross app
4. Try to add meross device/integration again, but no new devices are found.

**Comment by albertogeniola** [comment]
Hi!
Which Meross plug are you adding? Not all the Meross devices are supported by this plugin.

**Comment by charan28** [comment]
Hi there, I'm using the meross mss620 for all plugs (existing ones are working, new ones not found).

**Comment by albertogeniola** [comment]
Hi @charan28 ,
one thing is unclear to me. If you delete the integration from HA, then pair all your plugs to the Meross App and then install again the integration in HA, will all the plugs show? Or does HA show the same exact set of devices it showed before?

The point of that test is to determine whether the problem is about the integration not "seeing" new paired Meross devices or such new Meross devices not being compatible with the integration in the first place (is that case, it's perfectly legit to not be shown).
