### ISSUE TITLE
Problemas con actualización v1.2.13

### ISSUE THREAD

**Issue by AtonPC** [albertogeniola/meross-homeassistant#489]
**Describe the bug**
Se ha actualizado la app de Meross Cloud IoT a la versión 13 y no se conecta al cloud de Meross. Han dejado de funcionar todos los dispositivos y entidades. Intento añadir una nueva entrada y constantemente me dice que los credenciales son erróneos, cuando no es así, están correctos. 

He recargado la app y tampoco funciona. 

**Your environment**
Core 2024.2.2
Supervisor 2024.02.0
Operating System 11.5
Frontend 20240207.1

![image](https://github.com/albertogeniola/meross-homeassistant/assets/143940069/6dd5f193-b01f-4aca-acec-b7cfcd00ab7f)

![image](https://github.com/albertogeniola/meross-homeassistant/assets/143940069/f0aefb82-1ac6-4164-8b63-c32bfcf21cba)

**Comment by albertogeniola** [comment]
Hi @AtonPC ,

please write in english so that also other people can benefit from it :)

In any case, if I understood correctly, you are saying that the login fails when using your credentials and you are 100% sure those credentials are valid. If that's correct, please repeat the login attempt with valid credentials and report the HA logs reporting the specific error: you can find them in "Settings->System->Logs". Please attach the portion of logs being written when you get the credentials error.

**Comment by albertogeniola** [comment]
Closing as requested details have not been provided. Feel free to reopen when ready to gather the necessary information.
