### ISSUE TITLE
Unable to upgrade to 20200307.1 from 20200223.2

### ISSUE THREAD

**Issue by woody4165** [albertogeniola/meross-homeassistant#54]
Hi @albertogeniola 

I'm having problem upgrading to latest version 20200307.1 from 20200223.2 from HACS

When I try it does not update the installed field and, even if I restart Hassio, I see that is not updated.

What can I do to update?

Thanks

**Comment by albertogeniola** [comment]
Hi @woody4165 ,
first of all, would you please share your version of HACS? Have you updated HACS first?

In the meantime, you might perform a manual installation of the component rather than relying on HACS. [Instructions here](https://github.com/albertogeniola/meross-homeassistant#option-b-classic-installation-custom_component).

**Comment by woody4165** [comment]
Hi

When I posted the issue, the HACS version was 0.22.2 and there was no HACS update to install.

Now I see that there is a new version, 0.22.3 (came out 1hr ago) and after updating HACS, now your custom component has updated.

Thanks
