### ISSUE TITLE
Mail from meross

### ISSUE THREAD

**Issue by aferraz** [albertogeniola/meross-homeassistant#93]
Hi all,
 received this from meross:

This is meross cloud security team contacting you.
First of all, thanks for purchasing meross and we hope that you enjoy life with our smart products.
Recently our cloud security system has noticed that your devices are communicating with the could server at an extremely high frequency. We consider these behaviors abnormal and are concerned about the security of your devices.
Due to the security concerns and the intent to avoid any further potential damage, we will terminate the cloud services of these devices for now.
If you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to no more than one message every ten seconds and then send an email to <REDACTED>. We will resume cloud service for you within 24 hours. Please note that any abnormal high cloud request frequency will cause cloud service termination again.

**Comment by silviudc** [comment]
I wonder if #92 that I submitted is happening because of excessive polling also. Only started as of 0.110.4

**Comment by githubjles** [comment]
Same message from meross:
"Dear Customer,

This is meross cloud security team contacting you.
First of all, thanks for purchasing meross and we hope that you enjoy life with our smart products.
Recently our cloud security system has noticed that your devices are communicating with the could server at an extremely high frequency. We consider these behaviors abnormal and are concerned about the security of your devices.
Due to the security concerns and the intent to avoid any further potential damage, we will terminate the cloud services of these devices for now.
If you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to no more than one message every ten seconds and then send an email to <cloudservice@meross.com>. We will resume cloud service for you within 24 hours. Please note that any abnormal high cloud request frequency will cause cloud service termination again.
Should you have any information you would like to provide us with or would like to offer us any clarification, please contact us within 24 hours." 
And blocked me from accesing the sensors. 
How can I low the periodic request rate?
Thanks

**Comment by paulmgstone** [comment]
I have also received email three times. How do we adjust the periodic request rate as it just seems to affect thermostats which require cloud to work?

**Comment by albertogeniola** [comment]
Please update to the latest version (v1.0.0) which fixes the problem and introduces various improvements. Please follow update instructions [here](https://github.com/albertogeniola/meross-homeassistant#updating-from-legacy-versions).
